// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zocutgjmmwgowszvmpxf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpvY3V0Z2ptbXdnb3dzenZtcHhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwMjQwNTAsImV4cCI6MjA3MjYwMDA1MH0._CBQUK4TYRtPk-ZbvjvUKlRh3MUnIvX6M82-8xYRchc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});